### ISSUE TITLE
Handle all errors

### ISSUE THREAD

**Issue by wooorm** [Frankwarnaar/minor-persgroep#10]
...logging them doesn’t count.

[src/server/routes/index.js#L10-L12](https://github.com/Frankwarnaar/minor-persgroep/blob/de426faf432701899e88418d58a9081a8dd24bc0/src/server/routes/index.js#L10-L12)

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/Frankwarnaar/minor-persgroep/commit/9cf8afd7eceafd938c262128124913e3c6b8b292
