### ISSUE TITLE
Specify lint task

### ISSUE THREAD

**Issue by wooorm** [Frankwarnaar/minor-persgroep#6]
Currently, you’re using xo for linting, and it’s probably set-up in your editor (Atom, Sublime, Code?).
You should add a linting task in Gulp or npm, that makes sure other people that may contribute could also check their coding style?

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/Frankwarnaar/minor-persgroep/commit/71853837fe58c736d2a2dc9a3982d18917040072
