### ISSUE TITLE
Dollars in shell commands

### ISSUE THREAD

**Issue by wooorm** [Frankwarnaar/minor-persgroep#7]
In your documentation, you use the following to denote a shell script:

~~~console
```
$ git clone https://github.com/Frankwarnaar/minor-persgroep.git
$ npm install
$ npm run build
$ npm start
```
~~~

Those look quite nice, but people who may follow your walkthrough tend to copy-paste them into their console, which yields an error like the following:

```
🚀  ~: $ foo
-bash: $: command not found
```

I suggest removing the dollars, and adding a highlighting flag instead:

~~~console
```console
git clone https://github.com/Frankwarnaar/minor-persgroep.git
npm install
npm run build
npm start
```
~~~

**Comment by Frankwarnaar** [comment]
Resolved in https://github.com/Frankwarnaar/minor-persgroep/commit/a775829a483c7111ea805d5879c07788d1395736
