### ISSUE TITLE
Concatting paths together

### ISSUE THREAD

**Issue by wooorm** [Frankwarnaar/minor-persgroep#8]
Don’t [concat file-paths together](https://github.com/Frankwarnaar/minor-persgroep/blob/ec2539af2e2343f31753df671585b6dd51cb6a62/src/server/app.js#L35-L38):

```js
	.use(staticAsset(`${__dirname}/${baseDir}`))
	.use(express.static(`${__dirname}/${baseDir}`, {
		maxAge: 365 * 24 * 60 * 60
	}))
```

As this doesn’t work on Windows. Instead, use [`path.join`](https://nodejs.org/api/path.html#path_path_join_paths).

P.S. You can use slashes in `require()` calls!

**Comment by Frankwarnaar** [comment]
closed in https://github.com/Frankwarnaar/minor-persgroep/commit/170c407ae08004f4488bda8b7c5ae3dc334c131c

**Comment by wooorm** [comment]
~~contacting~~concatting*

Gah.

**Comment by Frankwarnaar** [comment]
What do you mean with "you can use slashes in `require()` calls"?

**Comment by wooorm** [comment]
`require('./foo/bar')` works on Windows too, but `fs.readFile('./foo/bar')` doesn’t (’cause Windows uses `\` instead of `/`)!
